# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pepin/UXP1A

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pepin/UXP1A

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pepin/UXP1A/CMakeFiles /home/pepin/UXP1A/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pepin/UXP1A/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CatchTests

# Build rule for target.
CatchTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CatchTests
.PHONY : CatchTests

# fast build rule for target.
CatchTests/fast:
	$(MAKE) -f CMakeFiles/CatchTests.dir/build.make CMakeFiles/CatchTests.dir/build
.PHONY : CatchTests/fast

#=============================================================================
# Target rules for targets named readlock

# Build rule for target.
readlock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 readlock
.PHONY : readlock

# fast build rule for target.
readlock/fast:
	$(MAKE) -f CMakeFiles/readlock.dir/build.make CMakeFiles/readlock.dir/build
.PHONY : readlock/fast

#=============================================================================
# Target rules for targets named lindatest

# Build rule for target.
lindatest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lindatest
.PHONY : lindatest

# fast build rule for target.
lindatest/fast:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/build
.PHONY : lindatest/fast

#=============================================================================
# Target rules for targets named writelock

# Build rule for target.
writelock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 writelock
.PHONY : writelock

# fast build rule for target.
writelock/fast:
	$(MAKE) -f CMakeFiles/writelock.dir/build.make CMakeFiles/writelock.dir/build
.PHONY : writelock/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

lib/src/example/readlock.o: lib/src/example/readlock.cpp.o

.PHONY : lib/src/example/readlock.o

# target to build an object file
lib/src/example/readlock.cpp.o:
	$(MAKE) -f CMakeFiles/readlock.dir/build.make CMakeFiles/readlock.dir/lib/src/example/readlock.cpp.o
.PHONY : lib/src/example/readlock.cpp.o

lib/src/example/readlock.i: lib/src/example/readlock.cpp.i

.PHONY : lib/src/example/readlock.i

# target to preprocess a source file
lib/src/example/readlock.cpp.i:
	$(MAKE) -f CMakeFiles/readlock.dir/build.make CMakeFiles/readlock.dir/lib/src/example/readlock.cpp.i
.PHONY : lib/src/example/readlock.cpp.i

lib/src/example/readlock.s: lib/src/example/readlock.cpp.s

.PHONY : lib/src/example/readlock.s

# target to generate assembly for a file
lib/src/example/readlock.cpp.s:
	$(MAKE) -f CMakeFiles/readlock.dir/build.make CMakeFiles/readlock.dir/lib/src/example/readlock.cpp.s
.PHONY : lib/src/example/readlock.cpp.s

lib/src/example/writelock.o: lib/src/example/writelock.cpp.o

.PHONY : lib/src/example/writelock.o

# target to build an object file
lib/src/example/writelock.cpp.o:
	$(MAKE) -f CMakeFiles/writelock.dir/build.make CMakeFiles/writelock.dir/lib/src/example/writelock.cpp.o
.PHONY : lib/src/example/writelock.cpp.o

lib/src/example/writelock.i: lib/src/example/writelock.cpp.i

.PHONY : lib/src/example/writelock.i

# target to preprocess a source file
lib/src/example/writelock.cpp.i:
	$(MAKE) -f CMakeFiles/writelock.dir/build.make CMakeFiles/writelock.dir/lib/src/example/writelock.cpp.i
.PHONY : lib/src/example/writelock.cpp.i

lib/src/example/writelock.s: lib/src/example/writelock.cpp.s

.PHONY : lib/src/example/writelock.s

# target to generate assembly for a file
lib/src/example/writelock.cpp.s:
	$(MAKE) -f CMakeFiles/writelock.dir/build.make CMakeFiles/writelock.dir/lib/src/example/writelock.cpp.s
.PHONY : lib/src/example/writelock.cpp.s

lib/src/file_manager.o: lib/src/file_manager.cpp.o

.PHONY : lib/src/file_manager.o

# target to build an object file
lib/src/file_manager.cpp.o:
	$(MAKE) -f CMakeFiles/CatchTests.dir/build.make CMakeFiles/CatchTests.dir/lib/src/file_manager.cpp.o
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/file_manager.cpp.o
.PHONY : lib/src/file_manager.cpp.o

lib/src/file_manager.i: lib/src/file_manager.cpp.i

.PHONY : lib/src/file_manager.i

# target to preprocess a source file
lib/src/file_manager.cpp.i:
	$(MAKE) -f CMakeFiles/CatchTests.dir/build.make CMakeFiles/CatchTests.dir/lib/src/file_manager.cpp.i
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/file_manager.cpp.i
.PHONY : lib/src/file_manager.cpp.i

lib/src/file_manager.s: lib/src/file_manager.cpp.s

.PHONY : lib/src/file_manager.s

# target to generate assembly for a file
lib/src/file_manager.cpp.s:
	$(MAKE) -f CMakeFiles/CatchTests.dir/build.make CMakeFiles/CatchTests.dir/lib/src/file_manager.cpp.s
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/file_manager.cpp.s
.PHONY : lib/src/file_manager.cpp.s

lib/src/linda.o: lib/src/linda.cpp.o

.PHONY : lib/src/linda.o

# target to build an object file
lib/src/linda.cpp.o:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/linda.cpp.o
.PHONY : lib/src/linda.cpp.o

lib/src/linda.i: lib/src/linda.cpp.i

.PHONY : lib/src/linda.i

# target to preprocess a source file
lib/src/linda.cpp.i:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/linda.cpp.i
.PHONY : lib/src/linda.cpp.i

lib/src/linda.s: lib/src/linda.cpp.s

.PHONY : lib/src/linda.s

# target to generate assembly for a file
lib/src/linda.cpp.s:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/linda.cpp.s
.PHONY : lib/src/linda.cpp.s

lib/src/main.o: lib/src/main.cpp.o

.PHONY : lib/src/main.o

# target to build an object file
lib/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/main.cpp.o
.PHONY : lib/src/main.cpp.o

lib/src/main.i: lib/src/main.cpp.i

.PHONY : lib/src/main.i

# target to preprocess a source file
lib/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/main.cpp.i
.PHONY : lib/src/main.cpp.i

lib/src/main.s: lib/src/main.cpp.s

.PHONY : lib/src/main.s

# target to generate assembly for a file
lib/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/main.cpp.s
.PHONY : lib/src/main.cpp.s

lib/src/parser.o: lib/src/parser.cpp.o

.PHONY : lib/src/parser.o

# target to build an object file
lib/src/parser.cpp.o:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/parser.cpp.o
.PHONY : lib/src/parser.cpp.o

lib/src/parser.i: lib/src/parser.cpp.i

.PHONY : lib/src/parser.i

# target to preprocess a source file
lib/src/parser.cpp.i:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/parser.cpp.i
.PHONY : lib/src/parser.cpp.i

lib/src/parser.s: lib/src/parser.cpp.s

.PHONY : lib/src/parser.s

# target to generate assembly for a file
lib/src/parser.cpp.s:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/parser.cpp.s
.PHONY : lib/src/parser.cpp.s

lib/src/tuple.o: lib/src/tuple.cpp.o

.PHONY : lib/src/tuple.o

# target to build an object file
lib/src/tuple.cpp.o:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/tuple.cpp.o
.PHONY : lib/src/tuple.cpp.o

lib/src/tuple.i: lib/src/tuple.cpp.i

.PHONY : lib/src/tuple.i

# target to preprocess a source file
lib/src/tuple.cpp.i:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/tuple.cpp.i
.PHONY : lib/src/tuple.cpp.i

lib/src/tuple.s: lib/src/tuple.cpp.s

.PHONY : lib/src/tuple.s

# target to generate assembly for a file
lib/src/tuple.cpp.s:
	$(MAKE) -f CMakeFiles/lindatest.dir/build.make CMakeFiles/lindatest.dir/lib/src/tuple.cpp.s
.PHONY : lib/src/tuple.cpp.s

tests/FileManagerTest.o: tests/FileManagerTest.cpp.o

.PHONY : tests/FileManagerTest.o

# target to build an object file
tests/FileManagerTest.cpp.o:
	$(MAKE) -f CMakeFiles/CatchTests.dir/build.make CMakeFiles/CatchTests.dir/tests/FileManagerTest.cpp.o
.PHONY : tests/FileManagerTest.cpp.o

tests/FileManagerTest.i: tests/FileManagerTest.cpp.i

.PHONY : tests/FileManagerTest.i

# target to preprocess a source file
tests/FileManagerTest.cpp.i:
	$(MAKE) -f CMakeFiles/CatchTests.dir/build.make CMakeFiles/CatchTests.dir/tests/FileManagerTest.cpp.i
.PHONY : tests/FileManagerTest.cpp.i

tests/FileManagerTest.s: tests/FileManagerTest.cpp.s

.PHONY : tests/FileManagerTest.s

# target to generate assembly for a file
tests/FileManagerTest.cpp.s:
	$(MAKE) -f CMakeFiles/CatchTests.dir/build.make CMakeFiles/CatchTests.dir/tests/FileManagerTest.cpp.s
.PHONY : tests/FileManagerTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CatchTests"
	@echo "... readlock"
	@echo "... lindatest"
	@echo "... writelock"
	@echo "... Catch2WithMain"
	@echo "... Catch2"
	@echo "... lib/src/example/readlock.o"
	@echo "... lib/src/example/readlock.i"
	@echo "... lib/src/example/readlock.s"
	@echo "... lib/src/example/writelock.o"
	@echo "... lib/src/example/writelock.i"
	@echo "... lib/src/example/writelock.s"
	@echo "... lib/src/file_manager.o"
	@echo "... lib/src/file_manager.i"
	@echo "... lib/src/file_manager.s"
	@echo "... lib/src/linda.o"
	@echo "... lib/src/linda.i"
	@echo "... lib/src/linda.s"
	@echo "... lib/src/main.o"
	@echo "... lib/src/main.i"
	@echo "... lib/src/main.s"
	@echo "... lib/src/parser.o"
	@echo "... lib/src/parser.i"
	@echo "... lib/src/parser.s"
	@echo "... lib/src/tuple.o"
	@echo "... lib/src/tuple.i"
	@echo "... lib/src/tuple.s"
	@echo "... tests/FileManagerTest.o"
	@echo "... tests/FileManagerTest.i"
	@echo "... tests/FileManagerTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

